package com.hms.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Data;

@Data
@Entity
@Table(name="Beds")
public class Beds
{
	
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)//Auto generated by id.
	private Long id;
	@Column
	private String name;
	@Column 
	private String type ;
	@Column
	private String description;
	

}
